In [24]:
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
root = "/project/wyin/jlee/ml-project/"
util_loc = os.path.join(root, "utils")
data_loc = os.path.join(root, "dos-prediction-full/data")
sys.path.append(util_loc)
from utilities import UnscaledData, ScaledData
import pickle
import time

In [17]:
scaled_data = ScaledData(data_loc, X_name = "params", y_name = "dos")
unscaled_data = UnscaledData(data_loc, X_name = "params", y_name = "dos")
train_X_scaled = scaled_data.train_X
train_y_scaled = scaled_data.train_y

train_X_unscaled = unscaled_data.train_X
train_y_unscaled = unscaled_data.train_y

n_train = len(train_X_scaled)
print(n_train)

106120


In [30]:
#Furthest points sampling with scaled distance
start = time.time()
used = np.full(n_train, False)
train_X_fps = [train_X_unscaled[0]]
train_y_fps = [train_y_unscaled[0]]

point = train_X_scaled[0]
index = 0
used[0] = True

for i in range(10):
    mx = 0
    mx_ind = -1
    for j, new_point in enumerate(train_X_scaled):
        if used[j]: continue
        
        dist = np.sum((new_point - point)**2)
        if dist > mx:
            mx_ind = j
            mx = dist
            
    point = train_X_scaled[mx_ind]
    used[mx_ind] = True
    
    train_X_fps.append(train_X_unscaled[mx_ind])
    train_y_fps.append(train_y_unscaled[mx_ind])
    
    if i % 100 == 0:
        print(mx)
    
train_X_fps = np.array(train_X_fps)
train_y_fps = np.array(train_y_fps)

print(time.time() - start)

15.803268047676664
6.843284606933594


In [31]:
print(train_X_fps)

[[ 0.06  -0.12   0.856]
 [-0.5    0.5    0.2  ]
 [ 0.5   -0.5    1.   ]
 [-0.5    0.5    0.216]
 [ 0.5   -0.5    0.984]
 [-0.5    0.48   0.2  ]
 [ 0.48  -0.5    1.   ]
 [-0.48   0.5    0.2  ]
 [ 0.48  -0.5    0.984]
 [-0.5    0.5    0.232]
 [ 0.5   -0.48   0.984]]
